terraform-aws-modules/terraform-aws-eventbridge

- README.md
- examples/api-gateway-event-source/README.md
- examples/api-gateway-event-source/main.tf
- examples/api-gateway-event-source/outputs.tf
- examples/complete/outputs.tf
- examples/default-bus/outputs.tf
- examples/with-archive/outputs.tf
- examples/with-permissions/README.md
- examples/with-permissions/outputs.tf
- outputs.tf
I don't think there is any value in "this_" anymore since this resource type+name is unique anyway in the module.
We will have to look on a per-module basis whether we should do the same in other modules also.
/cc @bryantbiggs
> feat: Simplified outputs (no this_)

- main.tf
The tomap call on empty map is not working on 0.15, which breakes the module.
The fix is just removing the call - and thats it.
Error message on 0.15.4:
```
╷
│ Error: Inconsistent conditional result types
│ 
│   on .terraform/modules/eventbridge/main.tf line 49, in resource "aws_cloudwatch_event_target" "this":
│   49:   for_each = var.create && var.create_targets ? {
│   50:     for target in local.eventbridge_targets : target.name => target
│   51:   } : tomap({})
│     ├────────────────
│     │ local.eventbridge_targets is tuple with 3 elements
│ 
│ The true result value has the wrong type: element types must all match for conversion to map.
╵
```
Module does not run on 0.15.x
none
> fix: Fix tomap call for terraform 0.15

- README.md
- iam.tf
- variables.tf
Attempt to fix #12 
If you're using the default eventbridge bus (required for scheduling), a role isn't attached. This is fine except for the ecs_target, which requires role_arn.
> fix: remove create_bus as a blocker for role_arn

- outputs.tf
`eventbridge_rule_ids` and `eventbridge_rule_arns` now return empty result when `create_rules` is set to `false`.
`create_rules = false` causes errors if any rules are defined.
See issue #18 
None.
I tested the change with the `default_bus` example as well as the production code that revealed the bug in the first place.
> fix: `create_rules = false` causes error

- main.tf
This PR adds support for using existing buses.  Instead of using the string `"default"` when `create_bus` is `false` the variable `bus_name` is used instead.  This variable defaults to the value `default` which should preserve its behavior.
I needed to be able to write rules against an existing bus and setting `create_bus` to `false` forced the use of the event bus named `default`.
I don't believe this introduces any breaking changes.
I deployed this against my own environment.  I was able to set `create_bus` to `false` and use the provided `bus_name` to target an existing event bus.
> feat: Support for existing event buses

- main.tf
This amends the ecs_target dynamic block to look in the correct way as it errored when target does not have an `ecs_target` block.
We found that not supplying an `ecs_target` to a target it complained that couldn't find `network_configuration` exact error:
```
Error: Unsupported attribute
on .terraform/modules/pipeline_event_bus/main.tf line 85, in resource "aws_cloudwatch_event_target" "this":
85:         for_each = lookup(each.value.ecs_target, "network_configuration", null) != null ? [
|----------------
| each.value is object with 6 attributes
This object does not have an attribute named "ecs_target".
```
This was intermittent and is hard to reproduce, our module usage did not contain an ecs_target configuration
No breaking changes
I modified the `examples/complete` with following …
> fix: Amend ecs_target network_configuration to work when no ecs_target supplied

- README.md
- examples/with-api-destination/.tool-versions
- examples/with-api-destination/README.md
- examples/with-api-destination/main.tf
- examples/with-api-destination/outputs.tf
- examples/with-api-destination/versions.tf
- examples/with-ecs-scheduling/main.tf
- iam.tf
- main.tf
- outputs.tf
- variables.tf
- versions.tf
- feat: support api destination
> feat: Added support for API destinations

- outputs.tf
When rules are configured but create=false, it causes applies to fail with an Invalid index error.
> fix: Fixed outputs when create=false

- main.tf
* Set the value of batch_target to be batch_target rather than true removing: `Can't access attributes on a primitive-typed value (bool)` error
When creating an event target got the error:
```
Error: Unsupported attribute
│ 
│   on .terraform/modules/pipeline_event_bus/main.tf line 116, in resource "aws_cloudwatch_event_target" "this":
│  116:       job_definition = batch_target.value.job_definition
│     ├────────────────
│     │ batch_target.value is true
│ 
│ Can't access attributes on a primitive-typed value (bool).
```
This change fixes this
None
- I have tested using our terraform to confirm it has fixed the issues experienced
> fix: Amend batch_target to be correct value

- .github/workflows/pr-title.yml
- .github/workflows/release.yml
- .github/workflows/stale-actions.yaml
- .pre-commit-config.yaml
- .releaserc.json
- examples/default-bus/README.md
- examples/default-bus/main.tf
- examples/default-bus/outputs.tf
- examples/with-archive/main.tf
- examples/with-archive/outputs.tf
- Update `.releaserc.json` to ensure conventional-commit standards are used by semantic-releaser
- Update `.pre-commit-config.yaml` versions to latest and ensure `end-of-file-fixer` hook is used
- Add `pr-title.yml` GitHub workflow for ensuring PR titles follow conventional-commit standards
- Fix `release.yml` GitHub workflow to ensure release process does not run on forks; ref https://github.com/terraform-aws-modules/meta/issues/25
- Add `stale-actions.yaml` to ensure issues and pull requests are routinely cleaned up; copie from EKS repository
- Ensure organization configurations are aligned and standardized; most of these changes are copied from the current EKS repository
- No
- CI checks only
> chore: Update release configuration files to correctly use conventional-commits

- README.md
It's `create_rules` everywhere in the code.
A simple README update
> chore: Fixed typo in `create_rules` in the README file

- main.tf
Remove boolean value inside dynamic "run_command_targets" for_each checker and made it usable for inputs.
AWS-RunShellScript event target requires that block for resource creating.
https://github.com/terraform-aws-modules/terraform-aws-eventbridge/issues/48
None.
> fix: Enable run_command_targets support for target

- README.md
- examples/complete/main.tf
- main.tf
- variables.tf
importing of already created rules fail due to the fact that the module appends a postfix to the name of the rule, connection, and API destination.
to make appending "-rule | -connection | -destination" optional we created 3 new bool variable by default it allows for postfix to be appended, when false is passed a value it will stop appending to the name .
an issue has been created #57 
its not a breaking change and it wont cause any compatibility issues .
- we forked this module made the needed changes and then imported our already existing rules without any issues or changes in the plan phase.
- we also updated one example (complete example) and added the **append_rule_postfix = false** to it .
> fix: Make it optional to append postfix to the name, connection, or API destination 

- iam.tf
- outputs.tf
Fixing two issues found:
1) The role_path is the same for role and policy if created by the AWS Console `"/service-role/"`, but when importing and trying do a plan, the plan wants to change the policy path to "/" (default)
2) When importing aws_cloudwatch_event_rule (if you have more than one), the second import fails, because terraform cannot find the resource (yet).
To be able to import the EventBridge rules (and dependencies) that has been created before.
N/A
Since this is hard to test (because depends on real resources to import) I tested locally
> fix: Problems found when importing resources previously already created

- iam.tf
This patch adds `Name` tag to IAM role and policies. Especially tags for policies are important because they're shown in Resource Groups & Tag Editor in `tag:Name` column in the default view.
> feat: Added Name tag for IAM policies and roles

- examples/with-ecs-scheduling/main.tf
Fix Inappropriate values for attribute "subnets" and "security_groups"
Fix Inappropriate values for attribute "subnets" and "security_groups" in the example folder **with-ecs-scheduling**
remove launch_type  FARGATE from ecs service resource as it requires network configuration
current behavior 
Inappropriate value for attribute "subnets": set of string required.
Inappropriate value for attribute "security_groups": set of string required.
No
Tested locally by applying the example
> fix: Fixed inappropriate values for subnets and security_groups in example

- .pre-commit-config.yaml
- README.md
- examples/complete/README.md
- examples/complete/main.tf
- main.tf
- variables.tf
Add default event bus schemas discoverer. This can supersede this [PR](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/pull/60).
Closes #60
This change is required since the event bus will not initialize after the creation
No breaking changes
this should do the same as before since the schemas discoverer is controlled by `create_schemas_discoverer` and is false by default
> feat: Add schema discoverer

- README.md
- variables.tf
> fix: Fixed misleading descriptions of IAM role (not Lambda)

- outputs.tf
Fix wrong value of api destination output.
> fix: Wrong value of api destination output

- .github/workflows/release.yml
The `Release` workflow is using an old version and hence a [deprecated runtime (Node.js 12)](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). Bumping these workflows will resolve the deprecation warning in the affected workflow.
Make sure that CI workflows uses non-deprecated runtimes.
None.
> chore: Upgrade CI workflow to use non-deprecated runtimes

- README.md
- main.tf
- variables.tf
To receive [events](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-events.html) from SaaS partner applications and services, you need a partner event source from the partner. Then you can create a partner [event bus](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-event-bus.html) and match it to the partner event source: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-saas.html
We wanted to add Auth0 as an SaaS partner integration to receive logs from Auth0's log stream.
I used the modified code to create the needed EventBridge Bus
> fix: Enable adding event_source_name to an Event Bus to enable receiving events from an SaaS partner

- README.md
- examples/api-gateway-event-source/README.md
- examples/api-gateway-event-source/versions.tf
- examples/complete/README.md
- examples/complete/versions.tf
- examples/default-bus/README.md
- examples/default-bus/versions.tf
- examples/with-api-destination/README.md
- examples/with-api-destination/versions.tf
- examples/with-archive/README.md
- examples/with-archive/versions.tf
- examples/with-ecs-scheduling/README.md
- examples/with-ecs-scheduling/main.tf
- examples/with-ecs-scheduling/versions.tf
- examples/with-lambda-scheduling/README.md
- examples/with-lambda-scheduling/versions.tf
- examples/with-permissions/README.md
- examples/with-permissions/versions.tf
- main.tf
- versions.tf
Adding some additional `ecs_target` arguments. 
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target#ecs_target
https://github.com/hashicorp/terraform-provider-aws/pull/28384
No.
> feat!: Bump Terraform version to 1.0 and updated `ecs_target` arguments

- examples/with-permissions/README.md
- examples/with-permissions/main.tf
- main.tf
This PR adds a new `condition_org` field to the `permissions` maps that will be used to set the `condition` section of the `aws_cloudwatch_event_permission` resource to allow limiting access to an EventBridge bus.
I wanted to be able to support more narrow permissions on an EventBridge bus akin to the examples shown in the terraform provider docs. Since complete map of `key`, `type` and `value` can't be passed in without making the entire variable an object, but `key` and `type` only have a single value, I opted to make the `value` the only field and set the remaining ones to their defaults when generating.
This change is backwards compatible
I modified the examples/with-permission module to deploy an event bus with access limited to only a single organization and then used the cli to …
> feat: Add support for setting the condition field in Event Bus permissions

- .pre-commit-config.yaml
- README.md
- examples/api-gateway-event-source/main.tf
- examples/complete/main.tf
- examples/default-bus/main.tf
- examples/with-api-destination/main.tf
- examples/with-archive/main.tf
- examples/with-ecs-scheduling/main.tf
- examples/with-lambda-scheduling/main.tf
- examples/with-permissions/main.tf
- iam.tf
- variables.tf
This pull request adds the `attach_sns_policy` flag to attach a permission policy to the sns target to allow the sending of event bridge notifications to sns. 
Without assigning resource permissions to the sns target, event bridge rule fails to send the notification to sns.
https://repost.aws/knowledge-center/sns-not-getting-eventbridge-notification
Fixes https://github.com/terraform-aws-modules/terraform-aws-eventbridge/issues/88
> feat: Add attach_sns_policy

- .pre-commit-config.yaml
- README.md
- examples/api-gateway-event-source/main.tf
- examples/complete/main.tf
- examples/default-bus/main.tf
- examples/with-api-destination/main.tf
- examples/with-archive/main.tf
- examples/with-ecs-scheduling/main.tf
- examples/with-lambda-scheduling/main.tf
- examples/with-permissions/main.tf
- examples/with-schedules/README.md
- examples/with-schedules/main.tf
- examples/with-schedules/outputs.tf
- examples/with-schedules/versions.tf
- iam.tf
- main.tf
- outputs.tf
- variables.tf
I have added basic support for the `aws_scheduler_schedule` resource type.
Eventbridge support in the module would be more complete with this functionality. Indeed it may not be perfect or complete, but hopefully this is a starting point for full scheduler support in addition to the existing features supported by the module. This [issue](https://github.com/terraform-aws-modules/terraform-aws-eventbridge/issues/81) exists for discussion as well.
Fixes #81
None.
> feat: Support for Eventbridge Scheduler Schedules

- main.tf
In several examples (api-gateway-event-source, with-archive, with-api-destination), any example where `bus_name` is known after apply (generated randomly in this case), there is an invalid count argument error:
```
Error: Invalid count argument
│ 
│   on ../../main.tf line 59, in data "aws_cloudwatch_event_bus" "this":
│   59:   count = (var.create && var.create_bus) || (var.bus_name == "") ? 0 : 1
│ 
│ The "count" value depends on resource attributes that cannot be determined until apply, so Terraform cannot predict how many instances will be created. To work
│ around this, use the -target argument to first apply only the resources that the count depends on.
╵
``` 
We can prevent this by removing the `|| (var.bus_name == "")` in the count conditional. 
`bus_name` defaults to `default` …
> fix: Event bus data source count conditional

- examples/with-pipes/main.tf
- main.tf
Add `input_template` inside `target_parameters` for pipes. 
Add example for using it in `dynamodb_stream_source_sqs_target`.
`input_template` can be specified for `target_parameters` to change the payload before sending it to the target.
No.
> feat: Add input_template in target_parameters for pipes

- .pre-commit-config.yaml
- README.md
- examples/complete/README.md
- examples/complete/main.tf
- examples/complete/outputs.tf
- main.tf
- outputs.tf
Fixes https://github.com/terraform-aws-modules/terraform-aws-eventbridge/issues/106
It is important to use `<<-EOF` to get rid of spaces. `chomp()` will cut the last newline.
> fix: Fixed newline handling in input_template

- examples/with-api-destination/main.tf
- main.tf
Allow API destinations to reuse the same connection. 
https://github.com/terraform-aws-modules/terraform-aws-eventbridge/issues/98
Closes: https://github.com/terraform-aws-modules/terraform-aws-eventbridge/issues/98
No.
> fix: Allow API destinations to reuse connections

- main.tf
Per AWS provider documentation,`input_paths` is not required.
Fixes #117 
Per the AWS Provider documentation on [aws_cloudwatch_event_target](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_target#input_transformer), `input_paths` is optional.
Scenario:
You have a rule of type "Scehduled Standard" and a target of a Batch job queue. You wish to use an `input_transformer` of type "Constant" and supply some static JSON for `input_template`. This means you will not have any need for `input_paths`. Currently the module _requires_ `input_paths` to be set.
Not that I am aware
I use this module at my place of employment and have tested this change with our implementation of this module and confirmed the change requested here does not break usage of the …
> fix: Made input_paths in input_transformer optional

- main.tf
Updated the aws_cloudwatch_event_rule resource definition in the Terraform configuration to replace the deprecated is_enabled attribute with the state attribute. This change ensures compatibility with the latest versions of the AWS provider.
This change is required to address deprecation warnings from the AWS provider for Terraform. The use of is_enabled has been deprecated and replaced by state, which is now required to define the enabled or disabled status of CloudWatch Event Rules.
Resolving this prevents potential issues with future versions of the AWS provider that may no longer support the is_enabled attribute, ensuring the stability and maintainability of the infrastructure code.
This change does not break backwards compatibility with the current major version of the module, as it …
> feat: Replace deprecated is_enabled with state in EventBridge rules

- main.tf
Changes the default value of `aws_cloudwatch_event_rule` to be `ENABLED` if neither the attributes `enabled` or `state` is set.
Fixes the issue introduces in v.3.3.0 https://github.com/terraform-aws-modules/terraform-aws-eventbridge/issues/121 where missing attributes defaults to the opposite value of the vanilla Terraform resource.
The change reestablished compatibility with Terraform defaults.
> fix: Default to null when state argument is not set

- outputs.tf
Atm with the aws provider this module fails as the event bridge connection output is sensitve but not declared as sensitive in the module
The output fails 
╷
│ Error: Output refers to sensitive values
│ 
│   on outputs.tf line 128:
│  128: output "eventbridge_connections" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was
│ intended to be only internal, Terraform requires that any root module
│ output containing sensitive data be explicitly marked as sensitive, to
│ confirm your intent.
│ 
│ If you do intend to export this data, annotate the output value as
│ sensitive by adding the following argument:
│     sensitive = true
> feat: Make eventbridge connections output sensitive

- README.md
- examples/api-gateway-event-source/README.md
- examples/api-gateway-event-source/main.tf
- examples/api-gateway-event-source/versions.tf
- examples/complete/README.md
- examples/complete/versions.tf
- examples/default-bus/README.md
- examples/default-bus/versions.tf
- examples/with-api-destination/README.md
- examples/with-api-destination/versions.tf
- examples/with-archive/README.md
- examples/with-archive/versions.tf
- examples/with-ecs-scheduling/README.md
- examples/with-ecs-scheduling/versions.tf
- examples/with-lambda-scheduling/README.md
- examples/with-lambda-scheduling/versions.tf
- examples/with-permissions/README.md
- examples/with-permissions/versions.tf
- examples/with-pipes/README.md
- examples/with-pipes/main.tf
- examples/with-pipes/versions.tf
- examples/with-schedules/README.md
- examples/with-schedules/versions.tf
- main.tf
- versions.tf
Support `aws_pipes_pipe` `log_configuration`. 
Added `force_destroy` to `aws_cloudwatch_event_target` and `aws_cloudwatch_event_rule`. 
Updated api-gateway module due to breaking major version changes. 
https://github.com/hashicorp/terraform-provider-aws/pull/37135
https://github.com/hashicorp/terraform-provider-aws/pull/34905
https://github.com/hashicorp/terraform-provider-aws/pull/37130
No.
> feat: Pipes log configuration support

- README.md
- iam.tf
- variables.tf
This PR addds the `policy_path` variable, to allow for the use of paths within the created iam policies.
The IAM Role currently supports paths but the policies are not, to be able to work nicely with permission boundaries and/or SCPs, it's preferable to have a path on the policies as well.
Fixes https://github.com/terraform-aws-modules/terraform-aws-eventbridge/issues/126
Should not have breaking changes, the default value is null, as is the default value of the provider.
Can test after working hours.
> feat: Added path parameter for aws_iam_policy resources

- examples/complete/main.tf
- examples/with-schedules/README.md
- examples/with-schedules/main.tf
- main.tf
Reopened #118 as the issue is still present. Let me know if you don't intend on merging these changes, then I'll stop reopening this one.
Before this change the target configuration for kinesis partition seems to be intended to look like this:
```terraform
kinesis_target = {
partition_key_path = “$.id”
}
```
Actually planning with this configuration present will error out though. Reason for this is that the for_each will assign the iterator to just `[true]` and subsequently try to access a field on it:
```
│ Error: Invalid function argument
│ 
│   on ../../main.tf line 200, in resource "aws_cloudwatch_event_target" "this":
│  200:       partition_key_path = lookup(kinesis_target.value, "partition_key_path", null)
│     ├────────────────
│     │ kinesis_target.value is true
│ 
│ Invalid …
```
> fix: Fix kinesis_target and kinesis_parameters dynamic blocks

- examples/with-schedules/README.md
- iam.tf
- iam_pipes.tf
Add `ecs:TagResource` to default ECS permissions
AWS is making a change to the `ecs:RunTask` API to allow customers to specify if tags can be set or not
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-account-settings.html#tag-resources-timeline
None
> feat: Updating default ECS policies to allow for Tagging

- README.md
- examples/with-ecs-scheduling/README.md
- examples/with-ecs-scheduling/main.tf
- iam.tf
- variables.tf
Allow specifying what roles can be passed using the PassRole action. 
Closes: https://github.com/terraform-aws-modules/terraform-aws-eventbridge/issues/128
No.
> feat: Allow specifying ecs policy passrole resources

- main.tf
Pipes requires permissions for source and target actions to be attached prior to creation otherwise the following error occurs (example of one from examples/with-pipes):
```
╷
│ Error: waiting for creation AWS EventBridge Pipes Pipe (sqs-source-lambda-target-pipe): unexpected state 'CREATE_FAILED', wanted target 'RUNNING, STOPPED'. last error: Input parameter is invalid from the request due to : The provided customer role does not have permissions to call ReceiveMessage on SQS
│ 
│   with module.eventbridge.aws_pipes_pipe.this["sqs_source_lambda_target"],
│   on ../../main.tf line 611, in resource "aws_pipes_pipe" "this":
│  611: resource "aws_pipes_pipe" "this" {
│ 
╵
```
Permissions are required to be attached to the pipes role prior to creation otherwise error occurs. 
No.
> fix: Add `depends_on` policy and policy attachments for pipes

- README.md
- examples/api-gateway-event-source/README.md
- examples/api-gateway-event-source/versions.tf
- examples/complete/README.md
- examples/complete/versions.tf
- examples/default-bus/README.md
- examples/default-bus/versions.tf
- examples/with-api-destination/README.md
- examples/with-api-destination/versions.tf
- examples/with-archive/README.md
- examples/with-archive/versions.tf
- examples/with-ecs-scheduling/README.md
- examples/with-ecs-scheduling/versions.tf
- examples/with-lambda-scheduling/README.md
- examples/with-lambda-scheduling/versions.tf
- examples/with-permissions/README.md
- examples/with-permissions/versions.tf
- examples/with-pipes/README.md
- examples/with-pipes/main.tf
- examples/with-pipes/versions.tf
- examples/with-schedules/README.md
- examples/with-schedules/versions.tf
- main.tf
- variables.tf
- versions.tf
Add `kms_key_identifier` to `aws_cloudwatch_event_bus`
Add `log_configuration.include_execution_data` arg for `aws_pipes_pipe`
https://github.com/hashicorp/terraform-provider-aws/pull/38569
https://github.com/hashicorp/terraform-provider-aws/pull/38492
No.
> feat: Adding `kms_key_identifier`to `aws_cloudwatch_event_bus` and `log_configuration.include_execution_data` to `aws_pipes_pipe`

- iam_pipes.tf
It looks like we're missing the states:StartSyncExecution action so we can execute step functions using the REQUEST_RESPONSE invocation_type
I was trying to use EB Pipes executing a step function using the REQUEST_RESPONSE invocation_type but getting the IAM error
```
{
"resourceArn": "arn:aws:pipes:eu-central-1:*:pipe/*-pipe",
"timestamp": 1726151215307,
"executionId": "*",
"messageType": "ExecutionFailed",
"logLevel": "ERROR",
"error": {
"message": "Target invocation failed with error from States. Not allowed to invoke arn:aws:states:eu-central-1:*:stateMachine:*.",
"httpStatusCode": 400,
"awsService": "states",
"requestId": "*",
"exceptionType": "AccessDenied",
"resourceArn": "arn:aws:states:eu-central-1:*:stateMachine:*"
}
}
```
and discovered it's not included
No
> feat: Update IAM pipes to support step function sync executions

- main.tf
As observed managed_streaming_kafka_parameters was missing from source parameters for aws_pipes_pipe resource in the module.
For serving the events from MSK topic to API destination via eventbridge pipe.
NO breaking changes , only add to support new source_parameter for MSK kafka.
Because it is necessary and valid source_parameter in the official resource for configuring managed_streaming_kafka_parameters pipes.
Supported Reference : [Link](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pipes_pipe#managed_streaming_kafka_parameters-1
We are using in our project and configuring the pipes from MSK to API Destination , already tested it is up and running no breaking changes occurred.
> feat: Added dynamic block for managed_streaming_kafka_parameters

- iam_pipes.tf
CloudWatch policy does not have proper resource and missing ability to use `log_configuration.cloudwatch_logs_log_destination`, targeting CloudWatch in pipes will result in:
```
"error": {
"message": "Target invocation failed with error from Logs. Not allowed to invoke.",
"httpStatusCode": 400,
"awsService": "logs",
"exceptionType": "AccessDenied",
},
```
Fixes issue https://github.com/terraform-aws-modules/terraform-aws-eventbridge/issues/136
No.
> fix: Cloudwatch policy for pipes

- README.md
- examples/with-pipes/README.md
- iam.tf
- iam_pipes.tf
- main.tf
- variables.tf
1. Fixes policy creation for step function enrichment
2. Adds a new variable to allow to create only the event bridge pipe role
The new variable allows to create the iam role only for pipe, for the cases where nothing else is created besides pipes, as for now you would end up with an additional role which is not needed
> fix: Step function enrichment

- iam_pipes.tf
Role path is not set for the resource aws_iam_policy.service
I work on a company who requires group path to be correctly set to be able to deploy.
> fix: Add role path to service `aws_iam_policy`

- main.tf
- Remove a mistakenly written brackets on block dynamic run_command_targets
The main purpose of this fix is to allow create targets for running ssm documents on ec2 instances. In my current company this change would be really appreciated.
Resolves #157
Doesn't break any other feature that this module covers
* it is worth to say that there is no example related to ssm as target rule. Someone else could give a try and write a one!
> fix: Event target for SSM (run_command_targets) should support an array of inputs

- main.tf
Add ECS task definition as target to EventBridge Pipes which is currently no supported.
ECS should be integrated with Eventbridge Pipes are its commonly used
No
+ resource "aws_pipes_pipe" "this" {
+ arn           = (known after apply)
+ description   = "Managed by Terraform"
+ desired_state = "RUNNING"
+ id            = (known after apply)
+ name          = "example-pipe-pipe"
+ name_prefix   = (known after apply)
+ role_arn      = "arn:aws:iam::xxxxx:role/service-role/Amazon_EventBridge"
+ source        = "arn:aws:sqs:ap-southeast-1:xxxxd:/abc-staging"
+ tags_all      = (known after apply)
+ target        = "arn:aws:ecs:ap-southeast-1:xxxxx:cluster/abc-staging"
+ source_parameters {
+ activemq_broker_parameters (known after apply)
+ dynamodb_stream_parameters (known after apply)
+ …
> feat: Enable ECS-Task as target in the EventBridge Pipes

- README.md
- examples/api-gateway-event-source/README.md
- examples/api-gateway-event-source/versions.tf
- examples/complete/README.md
- examples/complete/versions.tf
- examples/default-bus/README.md
- examples/default-bus/versions.tf
- examples/with-api-destination/README.md
- examples/with-api-destination/main.tf
- examples/with-api-destination/versions.tf
- examples/with-archive/README.md
- examples/with-archive/versions.tf
- examples/with-ecs-scheduling/README.md
- examples/with-ecs-scheduling/versions.tf
- examples/with-lambda-scheduling/README.md
- examples/with-lambda-scheduling/versions.tf
- examples/with-permissions/README.md
- examples/with-permissions/versions.tf
- examples/with-pipes/README.md
- examples/with-pipes/versions.tf
- examples/with-schedules/README.md
- examples/with-schedules/versions.tf
- main.tf
- variables.tf
- versions.tf
Support `dead_letter_config` for event buses and `kms_key_identifier` for event connections. 
- https://github.com/hashicorp/terraform-provider-aws/pull/42471
- https://github.com/hashicorp/terraform-provider-aws/pull/42385
No.
> feat: Event Bus DLQ and Event Connection CMK Encryption

- main.tf
For Managed Streaming for Kafka credentials, both [client_certificate_tls_auth](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pipes_pipe#client_certificate_tls_auth-1) and [sasl_scram_512_auth](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pipes_pipe#sasl_scram_512_auth-1) are optional. The current implementation does not allow using only one of them independently.
After this change, the following code will be valid for `source_parameters`:
```hcl
source_parameters = {
managed_streaming_kafka_parameters = {
topic_name = var.input_kafka_topic
batch_size = 10
credentials = {
sasl_scram_512_auth = var.msk_secret_arn
}
}
}
```
Currently, only the following form is accepted:
```hcl
source_parameters = { …
```
> fix: Usage of managed streaming kafka credentials

- examples/with-archive/main.tf
- examples/with-pipes/main.tf
- main.tf
- versions.tf
The Terraform AWS provider introduces the kms_key_identifier property for the "aws_cloudwatch_event_archive" resource. This is not yet set by the terraform-aws-eventbridge module
This enables users to set a custom kms key
No, not directly. Although I'm not yet sure how an existing archive reacts to re-keying. Might be worth mentioning.
> feat: Set kms_key_identifier for EventBridge archives
